### PR TITLE
Draft: Refactoring makefiles and adding CMake support

### PR DESCRIPTION
**Pull request by francoMU**
## Motivation

The current makefiles had the problem that they didn't resolve the dependecies correctly. This basically broke `make` capabilities of doing an easy rebuilt. Also most compiled projects rely now additionally on `CMake` which really speeds up development and compiling in different enviroments. Furthermore, I started adding some basic regression and unittests support.

## Features

- Refactored Makefiles
- CMake support
- Basic regression and unittest support

## Current Limitations

Currently, it is just possible to compile the core `lsms` program and not the Wang-Landau version. This can be easily added. Also the dependency generation was only tested for the gnu preprocessor at the moment. 

## Problems

- [ ] Missed mixing of magnetic moments. I seemed to have missed that during my rebasing

## TODOs

- [x] add README for make-based and the CMake based build system
- [x] add examples for Make-based build system and  CMake XSEDE cluster with and without GPU.
- [x] add regressions tests for common cases (non-spin polarized, spin-polarized and non-colinear)
- [x] check the mixer if nothing was lost
- [ ] add support for Wang-Landau
- [x] add a list of compilers that should be tested
- [x] refactor the current tests  to use the automatic testing capabilities of ctest
- [x] adding CI/CD with github action to test if building still works

### CODE REVIEW

**Comment by meisenbach** [comment]
Franco, great effort. The cleaning up of the header and source files is very useful and the addition of regression test will be great going forward. How does the addition of CMake affect the tradition build system with the architecture files?

**Comment by francoMU** [comment]
Generally, the CMake shouldn't affect the tradional make based system at all. However, I also slightly modified the tradional makefiles so that they can resolve the dependecies. I will add some examples for both cases.

**Review by meisenbach — APPROVED** [review]

**Comment by francoMU** [comment]
I will rebase the branch as long as changes are coming in on the master branch.

**Comment by meisenbach** [comment]
I am testing the Makefile based build system and will merge the changes in the main branch when I have constructed architecture files for compiling with Nvidia and AMD GPUs on the OLCF systems.

**Comment by francoMU** [comment]
Please give it a try. There are still a lot of things to do before the branch is mergeable. I haven't resolved all the problems yet.

**Comment by francoMU** [comment]
Could you provide the input that you used.

**Pull request merged**
